### ISSUE TITLE
The codebase is completely outdated

### ISSUE THREAD

**Issue by redochka** [prismicio/php-websitestarter#8]
Hello,

Dependencies are completely outdated.

Bumping prismic version break the code.

Is still the repository maintained? or accepting pull requests?

**Comment by srenault** [comment]
Hello,

This project is actually dead (`prismic-archive`). If you want to start a new php project with prismic, I'd recommend to follow this documentation: https://prismic.io/docs/php/getting-started/with-the-php-starter-kit
